name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Start Chat Server
      run: cargo run --bin server -- --listen 0.0.0.0:4433 > server.log &
      env:
        RUST_LOG: debug
    - name: wait server to start
      run: sleep 5
    - name: Run tests
      run: cargo test --verbose
    - name: Test Chat Client with Interactive Input
      run: cargo run --bin chat-client -- --server-addr 127.0.0.1:4433 --server-name localhost --name test-client &
      env:
        RUST_LOG: debug
    - name: Check Logs for Specific String
      run: |
        if ! grep "User test-client joined" server.log; then
          echo "String not found in logs. Halting workflow."
          exit 1
        fi
    - name: Ensure Client is Running
      run: pgrep -f chat-client
    - name: Ensure Server is Running
      run: pgrep -f chat-server
