name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Start Chat Server
      run: RUST_LOG=debug cargo run --bin server -- --listen 0.0.0.0:4433 &
      env:
        RUST_LOG: debug
    - name: Test Chat Client with Interactive Input
      run: |
        sleep 5 # Wait for the server to start
        cargo run --bin chat-client -- --server-name localhost --name test-client
    - name: Ensure Client is Running
      run: pgrep -f chat-client
    - name: Run tests
      run: cargo test --verbose
    - name: Ensure Server is Running
      run: pgrep -f chat-server
